<?php

declare(strict_types=1);

use Ecommpay\Hyva\ViewModel\EcpConfig;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var Escaper $escaper
 * @var Template $block
 * @var ViewModelRegistry $viewModels
 * @var EcpConfig $ecpConfig
 */
$magewire = $block->getMagewire();
$ecpConfig = $viewModels->require(EcpConfig::class);
?>
    <script>
        (() => {
            const displayMode = '<?= $escaper->escapeJs($ecpConfig->getCardDisplayMode()) ?>';
            const paymentPageVersion = '<?= $escaper->escapeJs($ecpConfig->getPaymentPageVersion()) ?>';
            const isPopupMode = displayMode === 'popup';
            const isEmbeddedMode = displayMode === 'embedded';
            const isEmbeddedV5 = isEmbeddedMode && paymentPageVersion === 'v5';
            const CHECK_VALIDATION_POST_MESSAGE = JSON.stringify({"message": "epframe.embedded_mode.check_validation","from_another_domain": true})
            const COMPONENT_ID = '<?= $escaper->escapeJs(str_replace('.after', '', $block->getNameInLayout())) ?>';
            let paymentPageParams = {};
            let ecommpayWidget = null;
            let pendingCheckSubmit = null;
            let validationResonseResolve = null;

            window.addEventListener('magewire:loader:start', () => {
                const overlay = document.querySelector('.magewire-loader-overlay');
                overlay?.classList.remove('pointer-events-none');
            });

            window.addEventListener('magewire:loader:done', () => {
                const overlay = document.querySelector('.magewire-loader-overlay');
                overlay?.classList.add('pointer-events-none');
            });

            function showOverlay() {
                window.dispatchEvent(new Event('magewire:loader:start'));
            }

            function hideOverlay() {
                window.dispatchEvent(new Event('magewire:loader:done'));
            }

            function enablePlaceOrderButton() {
                const btn = document.querySelector('button.btn-place-order');
                btn?.removeAttribute('disabled');
            }

            function findComponent() {
                try {
                    return Magewire.find(COMPONENT_ID);
                } catch (e) {
                    return null;
                }
            }

            function waitForComponent() {
                return new Promise((resolve) => {
                    if (findComponent()) {
                        resolve();
                        return;
                    }

                    Magewire.hook('component.initialized', component => {
                        if (component.id === COMPONENT_ID) {
                            resolve();
                        }
                    });
                });
            }

            async function fetchJson(uri, queryParams = {}, headers = {}, args = {}) {
                const url = new URL(uri, BASE_URL);
                url.search = new URLSearchParams({ ...queryParams, form_key: hyva.getFormKey() }).toString();
                return await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json', ...headers }, ...args});
            }

            async function fetchJsonWithTimeout(uri, queryParams, timeout) {
                const controller = new AbortController();
                const timeoutSignal = AbortSignal.timeout(timeout);
                return await fetchJson(uri, queryParams, {}, { signal: AbortSignal.any([controller.signal, timeoutSignal]) });
            }

            async function isCartAmountValid() {
                try {
                    const response = await fetchJson('ecommpay/startpayment/embeddedform', { action:'checkCartAmount', amount: paymentPageParams.payment_amount });
                    const result = await response.json();
                    return result.amountIsEqual === true;
                } catch (e) {
                    return false;
                }
            }

            async function restoreCartViaEndpoint() {
                try {
                    await fetchJson('ecommpay/endpayment/restorecart', {}, { 'X-Requested-With': 'XMLHttpRequest' })
                } catch (error) {}

                window.location.reload();
            }

            async function validatePaymentPageForm(timeout = 5000) {
                window.postMessage(CHECK_VALIDATION_POST_MESSAGE);
                return new Promise((resolve, reject) => {
                    setTimeout(() => {
                        reject(new Error('Timed out waiting for validation response.'));
                    }, timeout);

                    validationResonseResolve = resolve
                });
            }

            async function initEmbededMode() {
                if (displayMode !== 'embedded') {
                    return;
                }
                await loadMerchantJs();
                await waitForComponent();
                const component = findComponent();
                const response = await fetchJson('ecommpay/startpayment/embeddedform', { action: 'create'})
                const data = await response.json();
                if (response.ok && data.success === true) {
                    paymentPageParams = {...data.cardRedirectUrl};
                    delete paymentPageParams.paymentPageUrl;

                    if (isEmbeddedV5) {
                        initEmbeddedModeV5(component, paymentPageParams);
                    } else {
                        initEmbeddedModeV4(component, paymentPageParams);
                    }
                } else {
                    hyvaCheckout.message.alert('There was a technical problem starting the payment. Please try again.');
                }
            }

            async function initPopup() {
                const response = await fetchJson('ecommpay/startpayment/index', { method: 'card' })
                const data = await response.json();
                if (response.ok && data.success === true) {
                    const paymentPageParams = { ...data.paymentPageParams };
                    delete paymentPageParams.paymentPageUrl;

                    paymentPageParams.onPaymentSuccess = function () {
                        window.location.replace(config.merchant_success_url);
                    };

                    paymentPageParams.onPaymentFail = function () {
                        window.location.replace(config.merchant_fail_url);
                    };

                    window.EPayWidget.run(paymentPageParams);
                } else {
                    hyvaCheckout.message.alert('There was a technical problem starting the payment. Please try again.');
                }
            }

            function initEmbeddedModeV4(component, paymentPageParams) {
                paymentPageParams.onPaymentFail = function (data) {
                    hyvaCheckout.message.alert('There was an error processing the payment: ' + data?.payment?.result_message + '. Please try again or use a different card.');
                    waitForComponent().then(() => {
                        const freshComponent = findComponent();
                        if (freshComponent) {
                            freshComponent.call('cancelOrder').then(() => {
                                initEmbededMode();
                            });
                        } else {
                            initEmbededMode();
                        }
                    });
                };

                paymentPageParams.onEmbeddedModeRedirect3dsParentPage = function (data) {
                    const {method, url, body} = data;

                    const form = Object.assign(document.createElement('form'), {
                        method,
                        action: url,
                        style: 'display: none;',
                        name: '3dsForm'
                    });

                    Object.entries(body).forEach(([key, value]) => {
                        const input = Object.assign(document.createElement('input'), {name: key, value});
                        form.appendChild(input);
                    });

                    document.body.appendChild(form);
                    form.submit();
                };

                paymentPageParams.onEnterKeyPressed = function () {
                    const btn = document.querySelector('button.btn-place-order');
                    btn?.click();
                }

                paymentPageParams.onEmbeddedModeCheckValidationResponse = validationResonseResolve;

                hyvaCheckout.storage.setValue('ecommpayPaymentId', paymentPageParams.payment_id);
                window.EPayWidget.run(paymentPageParams);
            }

            function initEmbeddedModeV5(component, paymentPageParams) {
                paymentPageParams.onValidationError = function (errors) {
                    const messages = Object.values(errors).join('\n');
                    hyvaCheckout.message.alert(messages);
                    enablePlaceOrderButton();
                    pendingCheckSubmit = false;
                };

                paymentPageParams.onCheckSubmit = async function (data, resolve, reject) {
                    if (!pendingCheckSubmit) {
                        reject();
                        await hyvaCheckout.order.place();
                    } else {
                        await createOrderAndStartPayment(resolve, reject);
                        pendingCheckSubmit = false;
                    }
                };

                paymentPageParams.onPaymentFail = restoreCartViaEndpoint;

                paymentPageParams.onShowLoader = showOverlay;
                paymentPageParams.onHideLoader = hideOverlay;

                ecommpayWidget = window.EPayWidget.runEmbedded(paymentPageParams);
            }



            async function loadMerchantJs() {
                return new Promise( (resolve, reject) => {
                    if (!window.EPayWidget) {
                        const script = document.createElement('script');
                        script.src = '<?= $escaper->escapeUrl($magewire->paymentPageUrl) ?>/shared/merchant.js';
                        script.async = true;
                        script.onload = resolve;
                        script.onerror = () => {
                            reject();
                            hyvaCheckout.messenger.dispatch(
                                'payment:method',
                                "Couldn't load merchant.js library"
                            );
                        }

                        document.head.append(script);
                        const link = document.createElement('link');
                        link.rel = 'stylesheet';
                        link.href = '<?= $escaper->escapeUrl($magewire->paymentPageUrl) ?>/shared/merchant.css';
                        link.type = 'text/css';
                        document.head.append(link);
                    } else {
                        resolve();
                    }
                })
            }

            async function createOrderAndStartPayment(resolve, reject) {
                try {
                    await hyvaCheckout.main.getWireComponent().placeOrder(hyvaCheckout.storage.data);

                    const finished = hyvaCheckout.config.isSetFlag('navigator.finished') || false;

                    if (! finished) {
                        reject();
                        return;
                    }

                    showOverlay();
                    const response = await fetchJsonWithTimeout(
                        'ecommpay/startpayment/embeddedform', { action: 'onCheckSubmit', payment_id: paymentPageParams.payment_id }, 10000
                    );

                    const result = await response.json();
                    if (result.success && result.data) {
                        resolve({
                            payment_update: result.data.payment_update,
                            additional_parameters: result.data.additional_parameters
                        });
                    } else {
                        hideOverlay();
                        reject();
                    }
                } catch (error) {
                    hideOverlay();
                    reject();
                }
            }

            window.addEventListener('checkout:payment:method-activate', event => {
                if (event.detail.method !== 'ecommpay_card') {
                    return;
                }
                if (isEmbeddedMode || isPopupMode) {
                    loadMerchantJs().then(() => {
                        if (isEmbeddedMode) {
                            initEmbededMode();
                        }
                    });
                }
                hideOverlay();

                hyvaCheckout.payment.activate(
                    'ecommpay_card',
                    {
                        async validate() {
                            if (displayMode !== 'embedded') {
                                return true;
                            }

                            if (!await isCartAmountValid()) {
                                hyvaCheckout.messenger.dispatch(
                                    'payment:method',
                                    'Payment amount mismatch. Please try again.'
                                );
                                window.dispatchEvent(new Event('checkout:navigation:out-of-sync'));
                                return false;
                            }

                            if (isEmbeddedV5) {
                                return true;
                            }

                            try {
                                const data = await validatePaymentPageForm();
                                return data && Object.keys(data).length === 0;
                            } catch (error) {
                                hyvaCheckout.messenger.dispatch(
                                    'payment:method',
                                    error.message
                                );
                                return false;
                            }
                        },
                        placeOrderViaJs() {
                            return isPopupMode || isEmbeddedV5;
                        },
                        async placeOrder() {
                            if (isEmbeddedV5) {
                                if (ecommpayWidget && ecommpayWidget.trySubmit) {
                                    ecommpayWidget.trySubmit();
                                    pendingCheckSubmit = true;
                                }
                                return;
                            }
                            await hyvaCheckout.main.getWireComponent().placeOrder(hyvaCheckout.storage.data);
                            if (displayMode === "popup") {
                                await initPopup();
                            }
                        }
                    },
                    document.querySelector('#ecommpay-iframe-embedded')
                );
            });

            window.addEventListener('checkout:shipping:method-activate', initEmbededMode);

            Magewire.on('coupon_code_applied', initEmbededMode);
            Magewire.on('coupon_code_revoked', initEmbededMode);

            window.addEventListener('ecommpay:card:success', event => {
                const data = event.detail;
                const message = {"message": "epframe.embedded_mode.submit"};
                message.fields = data;
                message.from_another_domain = true;
                window.dispatchEvent(new Event('magewire:loader:start'));
                window.postMessage(JSON.stringify(message));
            });
        })();
    </script>
<?php isset($hyvaCsp) && $hyvaCsp->registerInlineScript() ?>
